server:
  port: 8080

spring:
  profiles:
    active: docker
  application:
    name: springBootService
  kafka:
    producer:
      bootstrap-servers: kafka:29092
    consumer:
      bootstrap-servers: kafka:29092
      group-id: myGroupId
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        prefer-ip-address: true
  datasource:
    url: jdbc:postgresql://postgres:5432/accountdb?serverTimezone=UTC
    username: user
    password: admin
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

